// Function to load tasks from localStorage
function loadTasks() {
    const tasks = JSON.parse(localStorage.getItem('tasks')) || []; // Get tasks from localStorage
    const taskList = document.getElementById('taskList');
    if (taskList) {
        tasks.forEach(task => {
            addTaskToDOM(task); // Add each task to the DOM
        });
    } else {
        console.error('taskList element not found');
    // Generated by Copilot
    
    document.addEventListener('DOMContentLoaded', (event) => {
        const taskInput = document.getElementById('taskInput');
        const addTaskButton = document.getElementById('addTaskButton');
        const taskList = document.getElementById('taskList');
    
        // Function to add a task
        function addTask() {
            const taskText = taskInput.value.trim();
            if (taskText !== '') {
                const li = document.createElement('li');
                li.textContent = taskText;
                taskList.appendChild(li);
                taskInput.value = '';
            }
        }
    
        // Event listener for the "Add Task" button
        addTaskButton.addEventListener('click', addTask);
    
        // Event listener for the "Enter" key
        taskInput.addEventListener('keypress', (event) => {
            if (event.key === 'Enter') {
                addTask();
            }
        });
    }

    // Generated by Copilot
});
}

// Function to move a task to the completed list
function moveToCompleted(task) {
    const completedList = document.getElementById('completedList'); // Get the completed list element

    if (task instanceof HTMLElement && completedList) {
        // Add animation
        task.style.transition = 'transform 0.5s ease, opacity 0.5s ease';
        task.style.transform = 'translateX(100%)'; // Move to the right
        task.style.opacity = 0; // Fade out

        setTimeout(() => {
            completedList.appendChild(task);
            task.style.transition = 'none'; // Reset for next click
            task.style.transform = 'none'; // Reset position
            task.style.opacity = 1; // Reset opacity
            removeTaskFromStorage(task.textContent.trim()); // Remove from localStorage
        }, 500); // Match the duration of the animation

        // Generated by Copilot
    } else {
        console.error('Invalid task or completedList not found');
    }
}

// Generated by Copilot

// Function to add a task to the DOM
function addTaskToDOM(taskText) {
    const li = document.createElement('li'); // Create a new list item
    li.textContent = taskText; // Set the text of the list item
    li.addEventListener('click', function() {
        moveToCompleted(this); // Move the task to the completed list
    });
    const taskList = document.getElementById('taskList');
    if (taskList) {
        taskList.appendChild(li); // Append the list item to the task list
    } else {
        console.error('taskList element not found');
    }
    // Generated by Copilot
}

// Function to save a task to localStorage
function saveTaskToStorage(taskText) {
    const tasks = JSON.parse(localStorage.getItem('tasks')) || []; // Get existing tasks
    tasks.push(taskText); // Add the new task
    localStorage.setItem('tasks', JSON.stringify(tasks)); // Save updated tasks to localStorage
}

// Function to remove a task from localStorage
function removeTaskFromStorage(taskText) {
    let tasks = JSON.parse(localStorage.getItem('tasks')) || []; // Get existing tasks
    tasks = tasks.filter(task => task !== taskText); // Filter out the removed task
    localStorage.setItem('tasks', JSON.stringify(tasks)); // Save updated tasks to localStorage
}

// Ensure DOM is fully loaded before running scripts
document.addEventListener('DOMContentLoaded', function() {
    // Add task button event listener
    document.getElementById('addTaskButton').addEventListener('click', function() {
        const taskInput = document.getElementById('taskInput'); // Get the input field
        const taskText = taskInput.value; // Get the value of the input field

        if (taskText) {
            addTaskToDOM(taskText); // Add task to the DOM
            saveTaskToStorage(taskText); // Save task to localStorage
            taskInput.value = ''; // Clear the input field
        }
    });

    // Load tasks when the page is loaded
    loadTasks();
});

// Generated by Copilot

// Generated by Copilot
